version: '3.9'

services:

  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_USERNAME=dev_user
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql-shard-0
      - mysql-shard-1
      - redis

  mysql-shard-0:
    image: mysql:8.0
    container_name: mysql-shard-0
    restart: always
    environment:
      MYSQL_DATABASE: url_shortener_0
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_0:/var/lib/mysql

  mysql-shard-1:
    image: mysql:8.0
    container_name: mysql-shard-1
    restart: always
    environment:
      MYSQL_DATABASE: url_shortener_1
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_1:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql_data_0:
  mysql_data_1: