spring.application.name=Url-Shortener

spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener_0
spring.datasource.username=dev_user
spring.datasource.password=Dev@2026#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

app.base-url=http://localhost:8080/api/v1/urls/

app.shards.datasource[0].url=jdbc:mysql://localhost:3307/url_shortener_0
app.shards.datasource[0].username=dev_user
app.shards.datasource[0].password=Dev@2026#

app.shards.datasource[1].url=jdbc:mysql://localhost:3308/url_shortener_1
app.shards.datasource[1].username=dev_user
app.shards.datasource[1].password=Dev@2026#