spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

app.base-url=http://localhost:8080/api/v1/urls/

app.shards.datasource[0].url=jdbc:mysql://mysql-shard-0:3306/url_shortener_0
app.shards.datasource[0].username=${DB_USERNAME}
app.shards.datasource[0].password=${DB_PASSWORD}

app.shards.datasource[1].url=jdbc:mysql://mysql-shard-1:3306/url_shortener_1
app.shards.datasource[1].username=${DB_USERNAME}
app.shards.datasource[1].password=${DB_PASSWORD}